export const MainActions = {
  GET_TODOS: 'GET_TODOS',
  ADD_TODO: 'ADD_TODO',
  ADD_TODOS: 'ADD_TODOS',
  TOGGLE_TODO: 'TOGGLE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
}

export const VisibilityFilters = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
};